### ISSUE TITLE
Error in TYPO3 7.6.5

### ISSUE THREAD

**Issue by ingeniumdesign** [koninklijke-collective/koning_mailchimp_signup#1]
Hi,

i have a Error in the Backend:
_Die Ausführung von Task "Extbase-CommandController-Task (extbase)" ist fehlgeschlagen mit folgender Meldung: MailChimp API wrapper not found. Run composer require drewm/mailchimp-api to install it._

and:
_Die Ausführung von Task "Extbase-CommandController-Task (extbase)" ist fehlgeschlagen mit folgender Meldung: MailChimp API wrapper not found. Run composer require drewm/mailchimp-api to install it and make sure vendor/autoload.php is included._

in the PlugIn is the Error: _Select from synced lists (run scheduler task if empty)_

i add the API-Key

**Comment by jp1987** [comment]
Have you run the command "composer require drewm/mailchimp-api"? Is your TYPO3 environment in composer mode? You might wanna check https://wiki.typo3.org/Composer. You could also include the https://github.com/drewm/mailchimp-api package manually.

**Comment by tyranni** [comment]
Sorry for the stupid question ;)
Unfortunately I could not use composer. So, I have to go the manually way. 
I don't understand where I have to put the "include('./MailChimp.php');" into. Into the setup.ts? Or into the configuration file of the "koning_mailchimp"-extension?
Would be very very happy if someone gives me a hint.

Thank you and best regards! :)

edit:
ok, trial and error ;) 
copied "include('./MailChimp.php');" in nearly every php file. nothing works :( 
would really appreciate some help. 
pleace! :*

**Comment by tyranni** [comment]
Finally I solved it. I did a plain typo3 installation locally on my home pc. On that machine i could install composer and use it to install DrewM's mailchimp-api-wrapper. After that I localized everything which was newly installed by the composer command to typo3's vendor folder and copied it into the vendor folder of my online system. Finally I edited 3 files in the vendor/composer folder: 
autoload_classmap.php 
(add 'DrewM\MailChimp\MailChimp' => $vendorDir . '/drewm/mailchimp-api/src/MailChimp.php'), 
autoload_psr4.php 
(add 'DrewM\MailChimp\' => array($vendorDir . '/drewm/mailchimp-api/src'))
and installed.json.
After all that I installed the koning_mailchimp_signup extension and everything worked. yay! :)

Maybe this will help someone who is desperately searching for some help like I was ;)

**Comment by bmoex** [comment]
Hi @tyranni,

Good to hear its working for you now. The idea of this extension is aimed for usage with composer. We are thinking of creating an composer extension that just includes this for our dependencies. However this is not something high on our priority list :-)

Thanks for the feedback and I'm closing this.

Kind regards,

Benjamin Serfhos
