### ISSUE TITLE
FE Form allowed Cache

### ISSUE THREAD

**Issue by ingeniumdesign** [koninklijke-collective/koning_mailchimp_signup#2]
hi, i install the plugin and it work nice, but I have the integrated plugin on each page, and now i have a problem with the Static file cache :(

> The page has a INTincScript: type: FUNC, userFunc: TYPO3\CMS\Extbase\Core\Bootstrap->run, extensionName: KoningMailchimpSignup, pluginName: Form

u can build a switch for cache enable?

**Comment by ingeniumdesign** [comment]
powermail have a BE Ext Config:
ext_conf_template.txt
enableCaching = 1

or the ext. fl_realurl_image
ext_conf_template.txt
cacheControl = 1

**Comment by jp1987** [comment]
This plugin does not work when it's fully cached, sorry.

**Comment by ingeniumdesign** [comment]
mhhhhhh i need that for the static-cache :(
